openapi: '3.0.0'
info:
  title: Flood API v3
  version: 3.0.0
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /api/v3/me:
    get:
      operationId: me
      summary: Return details for the currently signed in user
      responses:
        '200':
          description: |-
            200 OK
      security:
        - 'OAuth2':
            - 'admin'
servers:
  - url: https://api.flood.io
components:
  securitySchemes:
    OAuth2:
      description: 'OAuth2 scopes for Jira'
      type: 'oauth2'
      flows:
        clientCredentials:
          tokenUrl: 'https://api.flood.io/oauth/token'
          scopes:
            admin: 'The default admin scope'
            user: 'The default user scope'
